### ISSUE TITLE
Zooming in Preview-Window

### ISSUE THREAD

**Issue by tih2010** [jrebacz/NppGraphViz#1]
Hi there!!

NppGraohViz is great tool! Thank for sharing!

The only thing I miss is zoming in the preview window. My graphs quickly become too big for my monitor so I the preview window I can only see the upper part. 
I would be nice to zoom in and out by scrolling the mouse whee or something.

Best,
    Wolfram

**Comment by jrebacz** [comment]
Thanks for your feedback.  I'll try to fully close this issue next weekend.  In v1.0.1, I added the ability to scale down to fit the now resizable preview window.  That should help some, I'll add scroll bars and mouse wheel zooming later.

Thanks,
Jeff

**Comment by tih2010** [comment]
Great! I'v checked it out. That's a lot better already!
I'm looking forward to the scroll bars und mouse wheel zooming.

Thanks,
     Wolfram
