### ISSUE TITLE
What you see is NOT what you get

### ISSUE THREAD

**Issue by tih2010** [jrebacz/NppGraphViz#2]
Hi again!

I work a lot with NppGraphviz and my graphs grow and grow :-)

I just hit a very strange behavior: The picture shown in the preview window is totally different from the picture I get using File/Save as.

I guess this is related to the size of the graph, since it does not happen with my smaller graphs.

To make your debugging easyier I attached the graph. (It's a bit truncated to avoid pissing of my customers :-) )

[Strange.txt](https://github.com/jrebacz/NppGraphViz/files/262647/Strange.txt)

**Comment by jrebacz** [comment]
Yes, I see what you mean.  That is pretty strange.  I invoked GraphViz directly to compare the output:

dot -Tpng strange.txt -o image.png
dot -Tbmp strange.txt -o image.bmp

Those two images have different layouts.  They say dot is supposed to be deterministic, I guess not.  The preview is built with "dot -Tbmp", but NppGraphViz doesn't use that output for saving your file.  Instead, it rebuilds the graph with whatever format (-Txyz) you choose.  

As a workaround for now, if the other layout is worse than the preview window's version, try saving the image as .bmp and then converting that into your desired format.

**Comment by tih2010** [comment]
Wow!

I totally agree. Both of your commands should lead to the same image - just a different file format. There is nothing you can (or should :-) ) do about this. It's clearly a bug in graphviz itself and we should report it there!
