### ISSUE TITLE
Not Compatible with Notepad++ 64 bit?

### ISSUE THREAD

**Issue by KevinTyrrell** [jrebacz/NppGraphViz#4]
Notepad++ claims the 32-bit DLL is not compatible. What would be the steps to solve this?

**Comment by jrebacz** [comment]
Sorry about that.  I think Notepad++ was 32-bit only when I began this project.  Anyway, I updated the project to build 32-bit and 64-bit plugins.  You may download the latest 64-bit dll from the release section [https://github.com/jrebacz/NppGraphViz/releases/download/v1.0.3/NppGraphViz.dll](https://github.com/jrebacz/NppGraphViz/releases/download/v1.0.3/NppGraphViz.dll)

Happy Thanksgiving!
Jeff
