### ISSUE TITLE
Error about 32-bit dll

### ISSUE THREAD

**Issue by Kahdeg-15520487** [jrebacz/NppGraphViz#5]
After copying the dll file into notepad++'s plugins folder i restart notepad++ and got the following error.
![image](https://user-images.githubusercontent.com/15503419/35498741-15d3b598-0502-11e8-9609-ddff1a381c91.png)
Any way to fix this?
Thanks in advance.

**Comment by jrebacz** [comment]
Hello,
  Looks like you grabbed the 32-bit plugin, but you are running 64-bit Notepad++.  No problem. 
 Head over to https://github.com/jrebacz/NppGraphViz/releases then grab the 64-bit DLL (https://github.com/jrebacz/NppGraphViz/releases/download/v1.0.3/NppGraphViz.dll) and install it in the same location.  I'll update the instructions to be more clear on this.  Thanks!
