### ISSUE TITLE
Render bmp error when preview

### ISSUE THREAD

**Issue by yokarno** [jrebacz/NppGraphViz#6]
hello: 
  I installed 64bit nppGraphViz with 64bit-Notepad++ on Windows 10.  But when I want to preview, it shows:
Renderer type: "bmp" not recognized. Use one of: canon cmap cmapx dia dot fig gd gd2 gif hpgl imap ismap jpeg jpg mif mp pcl pic plain plain-ext png ps ps2 svg svgz vrml vtx wbmp xdot

But it works well when I use GraphViz directly,  could you please help me to check it ?

**Comment by jrebacz** [comment]
Hello,
That is strange!  The error:
> Renderer type: "bmp" not recognized. Use one of: canon cmap cmapx dia dot fig gd gd2 gif hpgl imap ismap jpeg jpg mif mp pcl pic plain plain-ext png ps ps2 svg svgz vrml vtx wbmp xdot

comes from GraphViz.  By default it uses dot.exe.  When the plugin tries to create a preview of your graph, it will make a call that is similar to this cmd line call: 

`C:\Program Files (x86)\Graphviz2.38\bin\dot -Tbmp < input.gv.txt > output.bmp `

I suggesting reinstalling the latest GraphViz, and checking that the NppGraphViz's config points to the latest version of GraphViz.  Most likely, that config lives here:
`C:\Users\<your user name>\AppData\Roaming\Notepad++\plugins\config\Graphviz.ini`
